//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject_Soft
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.project = new HashSet<project>();
        }
    
        public int Id_client { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string company { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<project> project { get; set; }
    }
}
