//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject_Soft
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.absence = new HashSet<absence>();
            this.avaible_vacantion_day = new HashSet<avaible_vacantion_day>();
            this.emp_project = new HashSet<emp_project>();
            this.post = new HashSet<post>();
            this.report = new HashSet<report>();
            this.schedule = new HashSet<schedule>();
        }
    
        public int Id_emp { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> emp_date { get; set; }
        public Nullable<int> hours { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<absence> absence { get; set; }
        public virtual ICollection<avaible_vacantion_day> avaible_vacantion_day { get; set; }
        public virtual ICollection<emp_project> emp_project { get; set; }
        public virtual ICollection<post> post { get; set; }
        public virtual ICollection<report> report { get; set; }
        public virtual ICollection<schedule> schedule { get; set; }
    }
}
