//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject_Soft
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DATA_TeamProjectSoftEntities : DbContext
    {
        public DATA_TeamProjectSoftEntities()
            : base("name=DATA_TeamProjectSoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<absence> absence { get; set; }
        public virtual DbSet<avaible_vacantion_day> avaible_vacantion_day { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<emp_project> emp_project { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<report> report { get; set; }
        public virtual DbSet<schedule> schedule { get; set; }
    }
}
