//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject_Soft
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.emp_project = new HashSet<emp_project>();
        }
    
        public int id_project { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> dead_line { get; set; }
    
        public virtual client client { get; set; }
        public virtual ICollection<emp_project> emp_project { get; set; }
    }
}
