//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamProject_Soft
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public schedule()
        {
            this.report = new HashSet<report>();
        }
    
        public int Id_schedule { get; set; }
        public Nullable<int> id_emp { get; set; }
        public Nullable<System.DateTime> arrival { get; set; }
        public Nullable<System.DateTime> departure_time { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual ICollection<report> report { get; set; }
    }
}
